name: issue_comment

on:
  issues:
    types: [opened]
  
  workflow_dispatch:


jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
          - name: Create Comment
            uses: peter-evans/create-or-update-comment@v1
            with:
                issue-number: ${{ github.event.issue.number }}
                body: |
                    Thanks for opening this issue!
                    - I will look into it ASAP.
                    - Stay tuned! 🚀
                